PLATFORMS = [
    {
        "name": "GitHub",
        "profile_url_template": "https://github.com/{username}",
        "check_method": "GET",
        "available_statuses": [404],
        "taken_statuses": [200],
        "unknown_statuses": [429, 403, 401],
    },
    {
        "name": "Reddit",
        "profile_url_template": "https://www.reddit.com/user/{username}",
        "check_method": "GET",
        "available_statuses": [404],
        "taken_statuses": [200],
        "unknown_statuses": [429, 403, 401],
        "headers": {
            "User-Agent": "Mozilla/5.0 (compatible; HandleScout/1.0; +https://example.com)",
        },
    },
    {
        "name": "TikTok",
        "profile_url_template": "https://www.tiktok.com/@{username}",
        "check_method": "GET",
        "available_statuses": [404],
        "taken_statuses": [200],
        "unknown_statuses": [429, 403, 401],
        "ambiguous_on_200": True,
    },
    {
        "name": "X (Twitter)",
        "profile_url_template": "https://x.com/{username}",
        "check_method": "GET",
        "available_statuses": [404],
        "taken_statuses": [200],
        "unknown_statuses": [429, 403, 401],
        "ambiguous_on_200": True,
    },
    {
        "name": "Discord",
        "profile_url_template": None,
        "check_method": None,
        "available_statuses": [],
        "taken_statuses": [],
        "unknown_statuses": [],
        "skip_check": True,
        "reason": "Discord does not provide reliable public username availability via URL",
    },
]
